trees:
  kernelci:
    url: "https://github.com/kernelci/linux.git"

# Common blocks
###############

clang-14-variant: &clang-14-variant
  clang-14:
    build_environment: clang-14
    architectures:
      arm64:
        base_defconfig: 'defconfig'
        fragments: [arm64-chromebook]
        filters:
          - passlist: { defconfig: ['arm64-chromebook'] }
      x86_64:
        base_defconfig: 'x86_64_defconfig'
        fragments: [x86-chromebook]
        filters:
          - passlist: { defconfig: ['x86-chromebook'] }

cros-filters: &cros-filters
  - regex: { defconfig: 'cros' }

arm-chromebook: &arm-chromebook
  filters: *cros-filters

arm64-chromebook: &arm64-chromebook
  fragments: [arm64-chromebook]
  filters: *cros-filters

x86_64-chromebook: &x86_64-chromebook
  fragments: [x86-chromebook]
  filters: *cros-filters

# Build variants
################

chromeos-variants-5_10: &chromeos-variants-5_10
  chromeos-clang-14:
    build_environment: clang-14
    architectures: &variants_architectures-5_10
      arm:
        << : *arm-chromebook
        base_defconfig: 'cros://chromeos-5.10/armel/chromiumos-arm.flavour.config'
        extra_configs:
          - 'cros://chromeos-5.10/armel/chromiumos-rockchip.flavour.config'
      arm64:
        << : *arm64-chromebook
        base_defconfig: 'cros://chromeos-5.10/arm64/chromiumos-arm64.flavour.config'
        extra_configs:
          - 'cros://chromeos-5.10/arm64/chromiumos-mediatek.flavour.config+arm64-chromebook'
          - 'cros://chromeos-5.10/arm64/chromiumos-qualcomm.flavour.config+arm64-chromebook'
          - 'cros://chromeos-5.10/arm64/chromiumos-rockchip64.flavour.config+arm64-chromebook'
      x86_64: &cros-arch_x86_64-5_10
        << : *x86_64-chromebook
        base_defconfig: 'cros://chromeos-5.10/x86_64/chromiumos-x86_64.flavour.config'
        extra_configs:
          - 'cros://chromeos-5.10/x86_64/chromeos-amd-stoneyridge.flavour.config+x86-chromebook'
          - 'cros://chromeos-5.10/x86_64/chromeos-intel-denverton.flavour.config+x86-chromebook'
          - 'cros://chromeos-5.10/x86_64/chromeos-intel-pineview.flavour.config+x86-chromebook'
          - 'cros://chromeos-5.10/x86_64/chromiumos-x86_64.flavour.config+x86-chromebook'
  << : *clang-14-variant


chromeos-variants-5_10-nocompress: &chromeos-variants-5_10-nocompress
  << : *chromeos-variants-5_10
  chromeos-clang-14:
    build_environment: clang-14
    architectures:
      << : *variants_architectures-5_10
      x86_64:
        << : *cros-arch_x86_64-5_10
        extra_configs:
          - 'cros://chromeos-5.10/x86_64/chromeos-amd-stoneyridge.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n'
          - 'cros://chromeos-5.10/x86_64/chromeos-intel-denverton.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n'
          - 'cros://chromeos-5.10/x86_64/chromeos-intel-pineview.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n'
          - 'cros://chromeos-5.10/x86_64/chromiumos-x86_64.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n'


chromeos-variants_5_15: &chromeos-variants-5_15
  chromeos-clang-14:
    build_environment: clang-14
    architectures: &variants_architectures-5_15
      arm:
        << : *arm-chromebook
        base_defconfig: 'cros://chromeos-5.15/armel/chromiumos-arm.flavour.config'
        extra_configs:
          - 'cros://chromeos-5.15/armel/chromiumos-rockchip.flavour.config'
      arm64:
        << : *arm64-chromebook
        base_defconfig: 'cros://chromeos-5.10/arm64/chromiumos-arm64.flavour.config'
        extra_configs:
          - 'cros://chromeos-5.15/arm64/chromiumos-mediatek.flavour.config+arm64-chromebook'
          - 'cros://chromeos-5.15/arm64/chromiumos-qualcomm.flavour.config+arm64-chromebook'
          - 'cros://chromeos-5.15/arm64/chromiumos-rockchip64.flavour.config+arm64-chromebook'
      x86_64: &cros-arch_x86_64-5_15
        << : *x86_64-chromebook
        base_defconfig: 'cros://chromeos-5.15/x86_64/chromiumos-x86_64.flavour.config'
        extra_configs:
          - 'cros://chromeos-5.15/x86_64/chromeos-amd-stoneyridge.flavour.config+x86-chromebook'
          - 'cros://chromeos-5.15/x86_64/chromeos-intel-denverton.flavour.config+x86-chromebook'
          - 'cros://chromeos-5.15/x86_64/chromeos-intel-pineview.flavour.config+x86-chromebook'
          - 'cros://chromeos-5.15/x86_64/chromiumos-x86_64.flavour.config+x86-chromebook'
  << : *clang-14-variant


chromeos-variants-5_15-nocompress: &chromeos-variants-5_15-nocompress
  << : *chromeos-variants-5_15
  chromeos-clang-14:
    build_environment: clang-14
    architectures:
      << : *variants_architectures-5_15
      x86_64:
        << : *cros-arch_x86_64-5_15
        extra_configs:
          - 'cros://chromeos-5.15/x86_64/chromeos-amd-stoneyridge.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n'
          - 'cros://chromeos-5.15/x86_64/chromeos-intel-denverton.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n'
          - 'cros://chromeos-5.15/x86_64/chromeos-intel-pineview.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n'
          - 'cros://chromeos-5.15/x86_64/chromiumos-x86_64.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n'

# Build configs
###############

build_configs:

  chromeos-next:
    tree: next
    branch: 'master'
    variants: *chromeos-variants-5_10

  chromeos-stable_5.10:
    tree: stable
    branch: 'linux-5.10.y'
    variants: *chromeos-variants-5_10-nocompress

  chromeos-stable_5.15:
    tree: stable
    branch: 'linux-5.15.y'
    variants: *chromeos-variants-5_15

  kernelci_chromeos-stable:
    tree: kernelci
    branch: 'chromeos-stable'
    variants: *chromeos-variants-5_10-nocompress
